# version: "3.9"

services:
  trading-api:
    build:
      context: .
      dockerfile: trading-api/Dockerfile
    env_file:
      - .env
    ports:
      - "${TRADING_API_SERVER_PORT}:${TRADING_API_SERVER_PORT}"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - motoo-network

  market-simulator:
    build:
      context: .
      dockerfile: market-simulator/Dockerfile
    env_file:
      - .env
    ports:
      - "${MARKET_SIMULATOR_SERVER_PORT}:${MARKET_SIMULATOR_SERVER_PORT}"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - motoo-network

  bot-engine:
    build:
      context: .
      dockerfile: bot-engine/Dockerfile
    env_file:
      - .env
    ports:
      - "${BOT_ENGINE_SERVER_PORT}:${BOT_ENGINE_SERVER_PORT}"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - motoo-network

  db:
    image: mysql:8.4.5
    container_name: motoo-local-db
    command:
      - "--bind-address=0.0.0.0"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - motoo-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7
    container_name: motoo-local-redis
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - motoo-network

  prometheus:
    image: prom/prometheus:latest
    env_file:
      - .env
    container_name: motoo-local-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    networks:
      - motoo-network

  grafana:
    image: grafana/grafana:latest
    env_file:
      - .env
    container_name: motoo-grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    networks:
      - motoo-network

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: motoo-mysql-exporter
    depends_on:
      - db
    volumes:
      - ./monitoring/.my.cnf:/etc/mysql/.my.cnf:ro
    command:
      - '--config.my-cnf=/etc/mysql/.my.cnf'
    ports:
      - "${MYSQL_EXPORTER_PORT}:${MYSQL_EXPORTER_PORT}"
    networks:
      - motoo-network

volumes:
  grafana-storage:

networks:
    motoo-network:
        driver: bridge