# version: "3.9"

services:
  trading-api:
    image: wodydl/motoo-trading-api
    env_file:
      - ${ENV_FILE}
    ports:
      - "${TRADING_API_SERVER_PORT}:${TRADING_API_SERVER_PORT}"
    depends_on:
      - db
      - redis

  market-simulator:
    image: wodydl/motoo-market-simulator
    env_file:
      - ${ENV_FILE}
    ports:
      - "${MARKET_SIMULATOR_SERVER_PORT}:${MARKET_SIMULATOR_SERVER_PORT}"
    depends_on:
      - db
      - redis

  bot-engine:
    image: wodydl/motoo-bot-engine
    env_file:
      - ${ENV_FILE}
    ports:
      - "${BOT_ENGINE_SERVER_PORT}:${BOT_ENGINE_SERVER_PORT}"
    depends_on:
      - db
      - redis

  db:
    image: mysql:8
    container_name: motoo-db
    environment:
      MYSQL_DATABASE: motoo
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  redis:
    image: redis:7
    container_name: motoo-redis
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  prometheus:
    image: prom/prometheus:latest
    container_name: motoo-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"

  grafana:
    image: grafana/grafana:latest
    container_name: motoo-grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"

volumes:
  grafana-storage: