# version: "3.9"

services:
  trading-api:
    build:
      context: .
      dockerfile: trading-api/Dockerfile
    env_file:
      - .env
    ports:
      - "${TRADING_API_SERVER_PORT}:${TRADING_API_SERVER_PORT}"
    depends_on:
      - db
      - redis

  market-simulator:
    build:
      context: .
      dockerfile: market-simulator/Dockerfile
    env_file:
      - .env
    ports:
      - "${MARKET_SIMULATOR_SERVER_PORT}:${MARKET_SIMULATOR_SERVER_PORT}"
    depends_on:
      - redis

  bot-engine:
    build:
      context: .
      dockerfile: bot-engine/Dockerfile
    env_file:
      - .env
    ports:
      - "${BOT_ENGINE_SERVER_PORT}:${BOT_ENGINE_SERVER_PORT}"
    depends_on:
      - redis

  db:
    image: mysql:8
    container_name: motoo-local-db
    environment:
      MYSQL_DATABASE: motoo
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  redis:
    image: redis:7
    container_name: motoo-local-redis
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"