spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  application:
    name: market-simulator

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    export:
      prometheus:
        enabled: true