server:
  port: ${BOT_ENGINE_SERVER_PORT:8082}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
logging:
  level:
    root: DEBUG
    org.springframework: INFO