name: CI - Develop

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Grant permission to execute gradlew
        run: chmod +x gradlew

      - name: 🔨 Build all modules
        run: ./gradlew build -x test
